version: 2

models:
  - name: users_view
    description: "A view that provides details about users."
    columns:
      - name: user_id
        description: "The unique identifier for a user."
        tests:
          - unique
          - not_null
      - name: username
        description: "The username of the user."
        tests:
          - not_null
      - name: email
        description: "The email address of the user."
        tests:
          - not_null

  - name: orders_view
    description: "A view that provides details about orders."
    columns:
      - name: order_id
        description: "The unique identifier for an order."
        tests:
          - unique
          - not_null
      - name: user_id
        description: "The user ID associated with the order."
        tests:
          - unique
          - not_null
      - name: product_name
        description: "The name of the product ordered."
        tests:
          - not_null
      - name: order_date
        description: "The date the order was placed."
        tests:
          - not_null

  - name: products_view
    description: "A view that provides details about products."
    columns:
      - name: product_id
        description: "The unique identifier for an product."
        tests:
          - unique
          - not_null
      - name: product_name
        description: "The name of the product producted."
        tests:
          - not_null
      - name: product_price
        description: "The price of the product."
        tests:
          - not_null

  - name: user_orders_view
    description: "A combined view of users and their orders."
    columns:
      - name: user_id
        description: "The unique identifier for a user."
        tests:
          - not_null
      - name: username
        description: "The username of the user."
      - name: order_id
        description: "The unique identifier for an order."
        tests:
          - not_null
      - name: product_name
        description: "The name of the product ordered."
      - name: order_date
        description: "The date the order was placed."

  - name: user_orders_products_view
    config:
      materialized: table
      tags: ['python']

    # Test the results of my Python transformation
    columns:
      - name: user_id
        # Standard validation for 'grain' of Python results
        tests:
          - not_null
  